bpf: fix build on some kernels
On some new kernels, the bpf code does not compile because some kernel
headers expect KBUILD_MODNAME to be defined.

Tested on Ubuntu 20.04.4 LTS with Linux 5.13.0-1023-azure.

Symptoms:

```
In file included from /.../sysdig/bpf/probe.c:22:
In file included from /.../sysdig/bpf/filler_helpers.h:13:
In file included from ./include/net/sock.h:59:
In file included from ./include/linux/filter.h:27:
In file included from ./include/net/sch_generic.h:21:
./include/net/flow_offload.h:324:4: error: use of undeclared identifier 'KBUILD_MODNAME'
                        NL_SET_ERR_MSG_MOD(extack, "Mixing HW stats types for actions is not supported");
                        ^
./include/linux/netlink.h:102:27: note: expanded from macro 'NL_SET_ERR_MSG_MOD'
        NL_SET_ERR_MSG((extack), KBUILD_MODNAME ": " msg)
```

Our BPF code does not use the functions using KBUILD_MODNAME, so it is
safe to set it to an arbitrary value to make it compile.

Signed-off-by: Alban Crequy <albancrequy@microsoft.com>